### ISSUE TITLE
hi, tired running it on xcode 7.1 and had a few error. any help or suggestions to solve these errors. thank you 

### ISSUE THREAD

**Issue by abdullefsay** [airrick213/GasShare#1]
![htmltree_h](https://cloud.githubusercontent.com/assets/16254708/11743026/46ed877a-9ffc-11e5-8de0-d5ca867688bf.png)

**Comment by airrick213** [comment]
After Apple updated to Swift 2.0 and XCode 7, my program has been unable to run, due to syntactical differences and whatnot. I have tried for hours to resolve the issue, but I ultimately admitted defeat. Fortunately, you can still download it off the App Store.

**Comment by abdullefsay** [comment]
thank you
